services:
  - type: web
    name: telegram-bot
    env: python
    pythonVersion: "3.11"
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        fromDatabase: false
